function(create_targets)
	add_library(OpenSSL::Crypto UNKNOWN IMPORTED)
	add_library(OpenSSL::SSL UNKNOWN IMPORTED)
	set_target_properties(OpenSSL::Crypto PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/include")
	set_target_properties(OpenSSL::SSL PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/include")
	if(EMSCRIPTEN)
		set_target_properties(OpenSSL::Crypto PROPERTIES
			IMPORTED_LINK_INTERFACE_LANGUAGES "C"
			IMPORTED_LOCATION "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/libx32/libcrypto.a")
		set_target_properties(OpenSSL::SSL PROPERTIES
			IMPORTED_LINK_INTERFACE_LANGUAGES "C"
			IMPORTED_LOCATION "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/libx32/libssl.a")
	endif(EMSCRIPTEN)
	if(ANDROID)
		set_target_properties(OpenSSL::Crypto PROPERTIES
			IMPORTED_LINK_INTERFACE_LANGUAGES "C"
			IMPORTED_LOCATION "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/lib/libcrypto.so")
		set_target_properties(OpenSSL::SSL PROPERTIES
			IMPORTED_LINK_INTERFACE_LANGUAGES "C"
			IMPORTED_LOCATION "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/lib/libcrypto.so")
	endif(ANDROID)
endfunction()

