name: release

run-name: ${{ github.actor }} ${{ github.event_name }} to ${{ github.base_ref }}
on:

  push:
    branches: [develop]      
jobs:
  build_test_package:
    runs-on: ubuntu-latest

    steps:

      - name: Build-install-openssl-dev
        uses : EddyTheCo/install-openssl-action/@develop
      
      - name: Package 
        working-directory: ${{ runner.temp }}/openssl-install
        run: |
          cmake -E make_directory ${{runner.temp}}/packages
          cmake -E tar c ${{runner.temp}}/packages/openssl-wasm.tar -- . 


      - uses: actions/upload-artifact@v3
        with:
          name: openssl-wasm
          path: ${{ runner.temp }}/packages/*


