name: release

run-name: ${{ github.actor }} ${{ github.event_name }} to ${{ github.base_ref }}
on:

  push:
    branches: [develop]
jobs:
  build_test_package:
    strategy:
      matrix:
        build_wasm: [true]
        build_android: ['none']
        include:
          - build_wasm: false
            build_android: 'android-arm'
          - build_wasm: false
            build_android: 'android-arm64'
    runs-on: ubuntu-latest

    steps:

      - name: Build-install-openssl-dev
        uses : EddyTheCo/install-openssl-action/@develop
        with:
          build_wasm: ${{ matrix.build_wasm }}
          build_android: ${{ matrix.build_android }}

      - name: Package
        working-directory: ${{ runner.temp }}/openssl-install
        run: |
          cmake -E make_directory ${{runner.temp}}/packages
          cmake -E tar c ${{runner.temp}}/packages/openssl-wasm_${{ matrix.build_wasm }}-android_${{ matrix.build_android }}.tar  -- .


      - uses: actions/upload-artifact@v4
        with:
          name: openssl-wasm_${{ matrix.build_wasm }}-android_${{ matrix.build_android }} 
          path: ${{ runner.temp }}/packages/*


