name: release

run-name: ${{ github.actor }} ${{ github.event_name }} to ${{ github.base_ref }}
on:

  push: 
    tags:
      - 'v*'  

  pull_request:
    branches: [develop]      
jobs:
  build_test_package:
    runs-on: ubuntu-latest

    steps:

      - name: Build-install-openssl-dev
        if: ( ! startsWith(github.ref, 'refs/tags/v') )
        uses : EddyTheCo/install-openssl-action/@test
      
      - name: Build-install-openssl-tag
        if: startsWith(github.ref, 'refs/tags/v')
        uses : EddyTheCo/install-openssl-action/@main

      - name: Package 
        working-directory: ${{ runner.temp }}/openssl-install
        run: |
          cmake -E make_directory ${{runner.temp}}/packages
          cmake -E tar c ${{runner.temp}}/packages/openssl-wasm.tar -- . 


      - uses: actions/upload-artifact@v3
        with:
          name: openssl-wasm
          path: ${{ runner.temp }}/packages/*


  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build_test_package
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
          
      - uses: actions/checkout@v3
    
      - uses: actions/download-artifact@v3
        with:
           path: artifacts
      - name: Display structure of downloaded files
        run: ls -R
          
      - name: Releases 
        uses: softprops/action-gh-release@v1
        with:
          files: ./artifacts/*/*       
